import {
  Archive,
  Baby,
  Bath,
  Bike,
  Blocks,
  BookOpen,
  Brush,
  Cake,
  Camera,
  Car,
  CircleDot,
  Coins,
  CookingPot,
  Cpu,
  Diamond,
  Dices,
  Disc3,
  Drum,
  Dumbbell,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  Glasses,
  Guitar,
  Headphones,
  House,
  Image,
  Keyboard,
  Landmark,
  Laptop,
  Layers,
  type LucideIcon,
  Mail,
  Monitor,
  Mouse,
  Music,
  Package,
  Palette,
  PartyPopper,
  Pencil,
  Piano,
  Puzzle,
  Scissors,
  Shapes,
  Shirt,
  ShoppingBag,
  SlidersHorizontal,
  Smartphone,
  Snowflake,
  Sofa,
  Sparkles,
  Speaker,
  SprayCan,
  Stamp,
  Sticker,
  Tent,
  ToyBrick,
  Trophy,
  Tv,
  Umbrella,
  UserRound,
  Utensils,
  Wallet,
  Watch,
  Waves,
} from 'lucide-react';

/** Icons shared across category and subcategory dropdown options. */
export const MARKETPLACE_CATEGORY_ICONS: Record<string, LucideIcon> = {
  Accessories: ShoppingBag,
  'Action figures & playsets': ToyBrick,
  Antiques: Landmark,
  Art: Palette,
  Audio: Headphones,
  'Baby shoes': Baby,
  'Babydoll dresses': Shirt,
  Bags: ShoppingBag,
  'Ball sports': CircleDot,
  'Ballet shoes': Footprints,
  Bandeaus: Shirt,
  'Bath & body': Bath,
  Beauty: Sparkles,
  Belts: Shirt,
  'Bikini and tankini bottoms': Waves,
  'Bikini and tankini sets': Waves,
  'Bikini and tankini tops': Waves,
  Blouses: Shirt,
  'Board games': Dices,
  'Boat shoes': Footprints,
  'Bodycon dresses': Shirt,
  Bodysuits: Shirt,
  Books: BookOpen,
  'Books & Media': BookOpen,
  Boots: Footprints,
  Bottoms: Shirt,
  'Boxers and briefs': Shirt,
  Bracelets: Diamond,
  Bras: Shirt,
  Brogues: Footprints,
  'Brooches & pins': Diamond,
  'Building sets & blocks': Blocks,
  'CDs & tapes': Disc3,
  'Cake decorating': Cake,
  'Cameras & film': Camera,
  'Camping & hiking': Tent,
  'Candles & holders': Flame,
  Cardigans: Shirt,
  'Cards, invitations & gift wrap': Mail,
  'Cars & vehicles': Car,
  'Casual dresses': Shirt,
  Ceramics: Shapes,
  Clogs: Footprints,
  'Clothing bundles': Package,
  Coats: Shirt,
  'Coats and jackets': Shirt,
  'Coins & currency': Coins,
  Collectibles: Trophy,
  Comics: BookOpen,
  'Computers & office': Monitor,
  Consoles: Gamepad2,
  Corsets: Shirt,
  Costume: Shirt,
  'Cover ups': Shirt,
  'Crop tops': Shirt,
  Cycling: Bike,
  'DJ & studio equipment': SlidersHorizontal,
  Decorations: Flower2,
  Desktops: Monitor,
  'Dinnerware & tableware': Utensils,
  'Dolls & accessories': ToyBrick,
  'Drawings & illustrations': Pencil,
  Dresses: Shirt,
  'Drums & percussion': Drum,
  'D\u00e9cor & home accessories': Flower2,
  Earrings: Diamond,
  Electronics: Monitor,
  Espadrilles: Footprints,
  'Everything else': Package,
  'Face masks & coverings': Shirt,
  Fashion: Shirt,
  Figurines: ToyBrick,
  Fitness: Dumbbell,
  'Flip flops': Footprints,
  Footwear: Footprints,
  'Formal dresses': Shirt,
  Fragrance: SprayCan,
  Furniture: Sofa,
  Games: Gamepad2,
  'Gaming accessories': Gamepad2,
  'Garden & outdoor': Flower2,
  Gloves: Shirt,
  'Going out dresses': Shirt,
  Golf: CircleDot,
  Grooming: Scissors,
  'Guitars & basses': Guitar,
  'Hair accessories': Sparkles,
  Haircare: SprayCan,
  'Hats and caps': Shirt,
  Headphones: Headphones,
  'Home & Garden': House,
  'Home audio & hi-fi': Speaker,
  Hoodies: Shirt,
  Jackets: Shirt,
  Jeans: Shirt,
  Jewelry: Diamond,
  'Jewelry & Watches': Diamond,
  Jumpsuits: Shirt,
  'Jumpsuits and rompers': Shirt,
  Keyboards: Keyboard,
  'Keyboards & pianos': Piano,
  Kids: Baby,
  'Kitchen accessories': CookingPot,
  'Laptop bags & cases': ShoppingBag,
  Laptops: Laptop,
  'Learning toys': Puzzle,
  Leggings: Shirt,
  Loafers: Footprints,
  Magazines: BookOpen,
  Makeup: Brush,
  Memorabilia: Trophy,
  Men: UserRound,
  'Mice & peripherals': Mouse,
  'Mixed media': Palette,
  Monitors: Monitor,
  'Movies & TV': Tv,
  Mules: Footprints,
  'Music & Instruments': Music,
  'Music accessories': Music,
  'Musical instruments': Music,
  Nails: Sparkles,
  Necklaces: Diamond,
  'Onesies and sleepers': Baby,
  Other: Package,
  'Other instruments': Music,
  Overalls: Shirt,
  Oxfords: Footprints,
  Paintings: Palette,
  Pajamas: Shirt,
  Panties: Shirt,
  Pants: Shirt,
  'Parts & components': Cpu,
  'Party favors': PartyPopper,
  'Party hats': PartyPopper,
  'Party supplies': PartyPopper,
  'Phone cases': Smartphone,
  'Phones & accessories': Smartphone,
  Photography: Camera,
  'Pins & patches': Sticker,
  'Polo shirts': Shirt,
  Prints: Image,
  'Prom dresses': Shirt,
  Pumps: Footprints,
  'Puzzles & games': Puzzle,
  'Racket sports': CircleDot,
  Rings: Diamond,
  Robes: Shirt,
  Rompers: Shirt,
  Sandals: Footprints,
  'Scarves and wraps': Shirt,
  Sculptures: Shapes,
  Shapewear: Shirt,
  'Shift dresses': Shirt,
  'Shirt dresses': Shirt,
  Shirts: Shirt,
  Shorts: Shirt,
  'Skates, skateboards & scooters': Footprints,
  Skincare: Sparkles,
  Skirts: Shirt,
  Sleepwear: Shirt,
  Slides: Footprints,
  Slippers: Footprints,
  'Small appliances': CookingPot,
  Sneakers: Footprints,
  Socks: Footprints,
  'Soft furnishings & textiles': Sofa,
  Speakers: Speaker,
  'Sports & Outdoors': Dumbbell,
  Stamps: Stamp,
  Stickers: Sticker,
  'Storage & organization': Archive,
  'Stuffed animals': ToyBrick,
  Suits: Shirt,
  'Summer dresses': Shirt,
  Sunglasses: Glasses,
  Sweaters: Shirt,
  Sweatpants: Shirt,
  Sweatshirts: Shirt,
  'Swim briefs and shorts': Waves,
  Swimsuits: Waves,
  Swimwear: Waves,
  'T-shirts': Shirt,
  'TVs & video': Tv,
  'Tailored jackets': Shirt,
  'Tailored trousers': Shirt,
  'Tank tops and camis': Shirt,
  'Tech accessories': Cpu,
  Tights: Shirt,
  'Tools & brushes': Brush,
  Tops: Shirt,
  'Toys & Games': Gamepad2,
  'Trading cards': Layers,
  Tuxedos: Shirt,
  Umbrellas: Umbrella,
  Undershirts: Shirt,
  Underwear: Shirt,
  Vests: Shirt,
  'Video games & consoles': Gamepad2,
  'Vinyl records': Disc3,
  'Wall d\u00e9cor': Image,
  'Wallets and cardholders': Wallet,
  Watches: Watch,
  'Water sports': Waves,
  'Wearable tech': Watch,
  'Wedding dresses': Shirt,
  'Winter sports': Snowflake,
  Women: UserRound,
  'Work dresses': Shirt,
  'Wrap dresses': Shirt,
};
